/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientDetails = IDL.Record({
  'additionalNotes' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SessionDetails = IDL.Record({
  'sessionType' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const ClientAlbum = IDL.Record({
  'id' : IDL.Nat,
  'photoUrls' : IDL.Vec(IDL.Text),
  'clientName' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'coverPhotoUrl' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'confirmed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'client' : ClientDetails,
  'paymentStatus' : PaymentStatus,
  'session' : SessionDetails,
  'timestamp' : Time,
  'photographerNotes' : IDL.Text,
  'proposedDateTime' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Nat),
});
export const PublicAlbumView = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'photoCount' : IDL.Nat,
  'coverPhotoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptBooking' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), IDL.Text], [], []),
  'addPhotoToAlbum' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createAlbum' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createBookingRequest' : IDL.Func(
      [ClientDetails, SessionDetails],
      [IDL.Nat],
      [],
    ),
  'createPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAlbum' : IDL.Func([IDL.Nat], [], []),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
  'denyBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllAlbums' : IDL.Func([], [IDL.Vec(ClientAlbum)], ['query']),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioItem' : IDL.Func([IDL.Nat], [IDL.Opt(PortfolioItem)], ['query']),
  'getReminders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, BookingRequest))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlbums' : IDL.Func([], [IDL.Vec(PublicAlbumView)], ['query']),
  'markBookingAsPaid' : IDL.Func([IDL.Nat], [], []),
  'removePhotoFromAlbum' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'retrieveAllBookingRequests' : IDL.Func(
      [],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'retrieveBookingRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BookingRequest)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBookingPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateAlbum' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updatePortfolioItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'verifyAlbumPassword' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientDetails = IDL.Record({
    'additionalNotes' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SessionDetails = IDL.Record({
    'sessionType' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const ClientAlbum = IDL.Record({
    'id' : IDL.Nat,
    'photoUrls' : IDL.Vec(IDL.Text),
    'clientName' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'coverPhotoUrl' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'confirmed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'client' : ClientDetails,
    'paymentStatus' : PaymentStatus,
    'session' : SessionDetails,
    'timestamp' : Time,
    'photographerNotes' : IDL.Text,
    'proposedDateTime' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Nat),
  });
  const PublicAlbumView = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'photoCount' : IDL.Nat,
    'coverPhotoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptBooking' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), IDL.Text], [], []),
    'addPhotoToAlbum' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createAlbum' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createBookingRequest' : IDL.Func(
        [ClientDetails, SessionDetails],
        [IDL.Nat],
        [],
      ),
    'createPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAlbum' : IDL.Func([IDL.Nat], [], []),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
    'denyBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllAlbums' : IDL.Func([], [IDL.Vec(ClientAlbum)], ['query']),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getReminders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, BookingRequest))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlbums' : IDL.Func([], [IDL.Vec(PublicAlbumView)], ['query']),
    'markBookingAsPaid' : IDL.Func([IDL.Nat], [], []),
    'removePhotoFromAlbum' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'retrieveAllBookingRequests' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'retrieveBookingRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BookingRequest)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBookingPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateAlbum' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updatePortfolioItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'verifyAlbumPassword' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };