/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientDetails = IDL.Record({
  'additionalNotes' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SessionDetails = IDL.Record({
  'sessionType' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'confirmed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'client' : ClientDetails,
  'paymentStatus' : PaymentStatus,
  'session' : SessionDetails,
  'timestamp' : Time,
  'photographerNotes' : IDL.Text,
  'proposedDateTime' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptBooking' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createBookingRequest' : IDL.Func(
      [ClientDetails, SessionDetails],
      [IDL.Nat],
      [],
    ),
  'createPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
  'denyBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioItem' : IDL.Func([IDL.Nat], [IDL.Opt(PortfolioItem)], ['query']),
  'getReminders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, BookingRequest))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markBookingAsPaid' : IDL.Func([IDL.Nat], [], []),
  'retrieveAllBookingRequests' : IDL.Func(
      [],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'retrieveBookingRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BookingRequest)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBookingPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updatePortfolioItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientDetails = IDL.Record({
    'additionalNotes' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SessionDetails = IDL.Record({
    'sessionType' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'confirmed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'client' : ClientDetails,
    'paymentStatus' : PaymentStatus,
    'session' : SessionDetails,
    'timestamp' : Time,
    'photographerNotes' : IDL.Text,
    'proposedDateTime' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptBooking' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createBookingRequest' : IDL.Func(
        [ClientDetails, SessionDetails],
        [IDL.Nat],
        [],
      ),
    'createPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
    'denyBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getReminders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, BookingRequest))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markBookingAsPaid' : IDL.Func([IDL.Nat], [], []),
    'retrieveAllBookingRequests' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'retrieveBookingRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BookingRequest)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBookingPrice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updatePortfolioItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };