/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'client' : ClientDetails,
  'paymentStatus' : PaymentStatus,
  'session' : SessionDetails,
  'timestamp' : Time,
  'photographerNotes' : string,
  'proposedDateTime' : [] | [string],
  'price' : [] | [bigint],
}
export type BookingStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'confirmed' : null } |
  { 'accepted' : null };
export interface ClientDetails {
  'additionalNotes' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type PaymentStatus = { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null };
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'timestamp' : Time,
  'category' : string,
}
export interface SessionDetails {
  'sessionType' : string,
  'date' : string,
  'time' : string,
  'description' : string,
  'location' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptBooking' : ActorMethod<[bigint, [] | [string], string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmBooking' : ActorMethod<[bigint, string], undefined>,
  'createBookingRequest' : ActorMethod<[ClientDetails, SessionDetails], bigint>,
  'createPortfolioItem' : ActorMethod<[string, string, string, string], bigint>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'denyBooking' : ActorMethod<[bigint, string], undefined>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioItem' : ActorMethod<[bigint], [] | [PortfolioItem]>,
  'getReminders' : ActorMethod<[], Array<[bigint, BookingRequest]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markBookingAsPaid' : ActorMethod<[bigint], undefined>,
  'retrieveAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'retrieveBookingRequest' : ActorMethod<[bigint], [] | [BookingRequest]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBookingPrice' : ActorMethod<[bigint, bigint], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];