/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'client' : ClientDetails,
  'paymentStatus' : PaymentStatus,
  'session' : SessionDetails,
  'timestamp' : Time,
  'photographerNotes' : string,
  'proposedDateTime' : [] | [string],
  'price' : [] | [bigint],
}
export type BookingStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'confirmed' : null } |
  { 'accepted' : null };
export interface ClientAlbum {
  'id' : bigint,
  'photoUrls' : Array<string>,
  'clientName' : string,
  'password' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'coverPhotoUrl' : string,
}
export interface ClientDetails {
  'additionalNotes' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type PaymentStatus = { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null };
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'timestamp' : Time,
  'category' : string,
}
export interface PublicAlbumView {
  'id' : bigint,
  'clientName' : string,
  'name' : string,
  'description' : string,
  'photoCount' : bigint,
  'coverPhotoUrl' : string,
}
export interface SessionDetails {
  'sessionType' : string,
  'date' : string,
  'time' : string,
  'description' : string,
  'location' : string,
}
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'createdAt' : Time,
  'quote' : string,
  'sport' : [] | [string],
  'approved' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptBooking' : ActorMethod<[bigint, [] | [string], string], undefined>,
  'addPhotoToAlbum' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmBooking' : ActorMethod<[bigint, string], undefined>,
  'createAlbum' : ActorMethod<[string, string, string, string, string], bigint>,
  'createBookingRequest' : ActorMethod<[ClientDetails, SessionDetails], bigint>,
  'createPortfolioItem' : ActorMethod<[string, string, string, string], bigint>,
  'createTestimonial' : ActorMethod<[string, string, [] | [string]], bigint>,
  'deleteAlbum' : ActorMethod<[bigint], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'denyBooking' : ActorMethod<[bigint, string], undefined>,
  'getAllAlbums' : ActorMethod<[], Array<ClientAlbum>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getApprovedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHeroBackground' : ActorMethod<[], string>,
  'getPortfolioItem' : ActorMethod<[bigint], [] | [PortfolioItem]>,
  'getReminders' : ActorMethod<[], Array<[bigint, BookingRequest]>>,
  'getTestimonial' : ActorMethod<[bigint], [] | [Testimonial]>,
  'getUnavailableDates' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAlbums' : ActorMethod<[], Array<PublicAlbumView>>,
  'markBookingAsPaid' : ActorMethod<[bigint], undefined>,
  'removePhotoFromAlbum' : ActorMethod<[bigint, string], undefined>,
  'retrieveAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'retrieveBookingRequest' : ActorMethod<[bigint], [] | [BookingRequest]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBookingPrice' : ActorMethod<[bigint, bigint], undefined>,
  'setHeroBackground' : ActorMethod<[string], undefined>,
  'setUnavailableDates' : ActorMethod<[Array<string>], undefined>,
  'toggleTestimonialApproval' : ActorMethod<[bigint], undefined>,
  'updateAlbum' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, [] | [string]],
    undefined
  >,
  'verifyAlbumPassword' : ActorMethod<[bigint, string], [] | [Array<string>]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];